# Generated by Django 5.2.1 on 2025-05-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
                ('employee_count', models.IntegerField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=12, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('hc_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'health_card',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('m_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20)),
                ('dosage', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('ts_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('u_id', models.OneToOneField(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('d_id', models.ForeignKey(db_column='d_id', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('p_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('prescription_date', models.DateField()),
                ('usage_info', models.CharField(max_length=100)),
                ('hc_id', models.ForeignKey(db_column='hc_id', on_delete=django.db.models.deletion.CASCADE, to='api.healthcard')),
                ('doc_id', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('u_id', models.OneToOneField(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hc_id', models.OneToOneField(db_column='hc_id', on_delete=django.db.models.deletion.CASCADE, to='api.healthcard')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.ForeignKey(db_column='ts_id', on_delete=django.db.models.deletion.CASCADE, to='api.timeslot')),
                ('doctor', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'db_table': 'appointment',
                'unique_together': {('patient', 'doctor', 'time_slot', 'date')},
            },
        ),
    ]
